@domain = http://localhost:3001
@AccessToken = {{loginToken.response.body.$.access_token}}


###
# 사용자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
 "email": "user@gmail.com",
  "password": "123qweQWE!"
 
}

###
# 컬럼 생성
POST {{domain}}/board/1/column
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "Done7"
}

###
# 컬럼 목록 조회
GET {{domain}}/board/1/column
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


###
# 컬럼 이름 수정
Patch {{domain}}/column/1/9
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name":"TodoList7"
}

###
# 컬럼 삭제
DELETE  {{domain}}/column/1/8
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###
# 컬럼 Index 이동
Patch {{domain}}/board/1/column/movebtn/3
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "moveBtn":"left"
}



###
# 드래그로 컬럼 이동
Patch {{domain}}/board/1/column/movedarg
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "columnIndex":[3,9,16,11,15]
}