@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.access_token}}

### 
# 사용자 회원가입
POST {{domain}}/user
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123qweQWE!",
  "username": "일반좁밥"
}

###
# 사용자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123qweQWE!"
}

###
# 사용자 정보 조회
GET {{domain}}/user/profile
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 엑세스 토큰 재발급 (로그인 시간 연장)
# @name loginToken
POST {{domain}}/auth/refresh
Authorization: Bearer {{AccessToken}}

###
# 사용자 정보 업데이트 - imageFile
PATCH {{domain}}/user
Authorization: Bearer {{AccessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="currentPassword"

123qweQWE!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="newPassword"

123qweQWE!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

감자국 명예신민
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="comment"

코멘트다 짜샤!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 
# 사용자 삭제
DELETE {{domain}}/user
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###
# 메일 인증번호 전송
# @name loginToken
POST {{domain}}/auth/send-verification
Content-Type: application/json

{
  "email": "user@gmail.com"
}

###
# 메일 인증번호 검증
# @name loginToken
POST {{domain}}/auth/verify-email
Content-Type: application/json

{
  "email": "user@gmail.com",
  "code": "t8s4ak"
}
###
# 카드 생성
POST {{domain}}/cards
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "제목",
  "description": "내용",
  "color": "F000000",
  "dueDate": "2024-01-12 23:00:00",
  "cardOrder": 1
}

###
# 카드 수정
PATCH {{domain}}/cards/3
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "제목 수정",
  "description": "내용 수정",
  "color": "F000000",
  "dueDate": "2024-01-12 23:00:00"
}

###
# 카드 삭제
DELETE {{domain}}/cards/3
Authorization: Bearer {{AccessToken}}

